- name: gatsby-playbook
  hosts: ec2
  become: yes
  tasks:

  - name: Effacement répertoire Gatsby
    shell: 
      cmd: sudo rm -rf /home/ec2-user/gatsby
    delegate_to: 127.0.0.1
    run_once: yes

  - name: Installation d'apache
    yum:
      name: httpd
      state: present

  - name: Installation du compilateur et make
    yum:
      name:
        - gcc-c++
        - make
      state: present

  - name: Installation de node et npm
    yum:
      name: nodejs
      state: present
      enablerepo: epel

  - name: Installation de Gatsby CLI
    npm:
      name: gatsby-cli
      global: yes
    delegate_to: 127.0.0.1
    run_once: yes
    
  - name: Création d'un répertoire
    shell: 
      cmd: mkdir /home/ec2-user/gatsby/
    delegate_to: 127.0.0.1
    run_once: yes

  - name: Clonage du repository with separate git directory
    git:
      repo: https://github.com/Mohamed-Benguerraiche/gatsby-starter-default.git
      dest: /home/ec2-user/gatsby/
    delegate_to: 127.0.0.1
    run_once: yes

  - name: Npm install
    shell: 
      cmd: npm install
      chdir: /home/ec2-user/gatsby
    delegate_to: 127.0.0.1
    run_once: yes

  - name: Build du projet
    shell: 
      cmd: gatsby build
    delegate_to: 127.0.0.1
    run_once: yes