- name: gatsby-playbook
  hosts: ec2
  become: true
  tasks:
  - name: Installation d'apache
    yum:
      name: httpd
      state: present

  - name: Installation du compilateur et make
    yum:
      name:
        - gcc-c++
        - make
      state: present

  - name: Installation de node et npm
    yum:
      name: nodejs
      state: present
      enablerepo: epel

  - name: Change di
    shell:
      cmd: ansible-playbook gatsby-playbook.yml -i hosts.ini
      chdir: ansible_aws/
    delegate_to: 127.0.0.1
    run_once: yes