- name: ansible-playbook
  hosts: ec2 #Liste des hôtes dans le fichier hosts
  become: true #Elévation des privilèges
  tasks:
  - name: Compilateur et make
    ansible.builtin.yum:
      - name:
          - gcc-c++
          - make
        state: present

  - name: Installer node et npm
    ansible.builtin.yum:
      name: nodejs
      state: present
      enablerepo: epel

  - name: Installer Gatsby
    ansible.builtin.npm:
      name: gatsby-cli
      global: yes