- name: gatsby-playbook
  hosts: ec2
  become: yes
  tasks:

  - name: Effacement répertoire Gatsby
    shell: 
      cmd: sudo rm -rf /home/ec2-user/gatsby
    delegate_to: 127.0.0.1
    run_once: yes

  - name: Installation d'apache
    yum:
      name: httpd
      state: present

  - name: Installation du compilateur et make
    yum:
      name:
        - gcc-c++
        - make
      state: present

  - name: Installation de node et npm
    yum:
      name: nodejs
      state: present
      enablerepo: epel

  - name: Installation de Gatsby CLI
    npm:
      name: gatsby-cli
      global: yes
    delegate_to: 127.0.0.1
    run_once: yes
    
  - name: Création d'un répertoire
    shell: 
      cmd: mkdir /home/ec2-user/gatsby
    delegate_to: 127.0.0.1
    run_once: yes

  - name: Clonage du repository with separate git directory
    git:
      repo: https://github.com/Mohamed-Benguerraiche/gatsby-starter-default.git
      dest: /home/ec2-user/gatsby
    delegate_to: 127.0.0.1
    run_once: yes

  - name: Installation des dépendances avec npm
    shell: npm install
    args:
      chdir: /home/ec2-user/gatsby
    delegate_to: 127.0.0.1
    async: 300
    poll: 0
    register: npm_install_job

  - name: Attendre la fin de l'installation npm
    async_status:
      jid: "{{ npm_install_job.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: 4  # Ajoutez le nombre de tentatives souhaité
    delay: 10    # Ajoutez l'intervalle entre les tentatives souhaité

  - name: Afficher la sortie de npm install
    debug:
      var: job_result.stdout_lines
    when: job_result.failed

  - name: Build du projet
    shell: 
      cmd: gatsby build
    args:
      chdir: /home/ec2-user/gatsby
    delegate_to: 127.0.0.1
    run_once: yes