- name: gatsby-playbook
  hosts: ec2
  become: yes
  tasks:

  - name: Effacement du répertoire Gatsby
    shell: 
      cmd: sudo rm -rf /home/ec2-user/gatsby
    delegate_to: 127.0.0.1
    run_once: yes

  - name: Installation d'apache
    yum:
      name: httpd
      state: present

  - name: Installation du compilateur et make
    yum:
      name:
        - gcc-c++
        - make
      state: present

  - name: Installation de node et npm
    yum:
      name: nodejs
      state: present
      enablerepo: epel

  - name: Installation de Gatsby CLI
    npm:
      name: gatsby-cli
      global: yes
    delegate_to: 127.0.0.1
    run_once: yes
    
  - name: Création d'un répertoire
    shell: 
      cmd: mkdir /home/ec2-user/gatsby
    delegate_to: 127.0.0.1
    run_once: yes

  - name: Clonage du repository vers /home/ec2-user/gatsby
    git:
      repo: https://github.com/Mohamed-Benguerraiche/gatsby-starter-default.git
      dest: /home/ec2-user/gatsby
    delegate_to: 127.0.0.1
    run_once: yes

  - name: Installation des dépendances avec npm dans /home/ec2-user/gatsby
    shell: npm install
    args:
      chdir: /home/ec2-user/gatsby
    delegate_to: 127.0.0.1
    register: npm_install_result

  - name: Affichage de la sortie de npm install
    debug:
      var: npm_install_result.stdout_lines
    when: npm_install_result.failed

  - name: Build du projet dans /home/ec2-user/gatsby
    shell: 
      cmd: gatsby build
    args:
      chdir: /home/ec2-user/gatsby
    delegate_to: 127.0.0.1
    run_once: yes