- name: ansible-playbook
  hosts: ec2
  become: true
  tasks:
  - name: Installer d'apache
    ansible.builtin.yum:
      name: httpd
      state: present

  - name: Installer le compilateur et make
    ansible.builtin.yum:
      - name:
          - gcc-c++
          - make
        state: present

  - name: Installer node et npm
    ansible.builtin.yum:
      name: nodejs
      state: present
      enablerepo: epel

  - name: Installer Gatsby
    ansible.builtin.npm:
      name: gatsby-cli
      global: yes